name: 'Deploy WebApp 452'

on:
  workflow_run:
    workflows: ["CI WebApp 452"]
    types: [completed]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab 

env:
  PACKAGE_NAME: 'webapp'

jobs:

  deploy-to-webserver:
    name: 'Deploy Package to IIS'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest  

    steps:

    - name: 'Download Artifact'
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
        name: ${{ env.PACKAGE_NAME }}

    - name: 'Deploy' 
      shell: cmd
      run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:package=WebApp452.zip -allowUntrusted -dest:auto,computerName="https://${{ secrets.WEBDEPLOY_HOST }}/msdeploy.axd?site=${{ secrets.WEBDEPLOY_SITENAME }}",username="${{ secrets.WEBDEPLOY_USERNAME }}",password="${{ secrets.WEBDEPLOY_PASSWD }}",AuthType="Basic" -verbose -setParam:name="IIS Web Application Name",value=${{ secrets.WEBDEPLOY_SITENAME }} -enableRule:DoNotDeleteRule'