name: 'Deploy WebApp 452'

on:
  workflow_run:
    workflows: ["CI WebApp 452"]
    types: [completed]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab 

env:
  APP_NAME: 'hellomvc5-webapp452'
  
jobs:

  deploy-to-azure:
    name: 'Deploy to Azure'
    runs-on: windows-latest
    needs: build-and-publish
    steps:    
    - name: "Download Artifact from Build Job"
      uses: actions/download-artifact@v3
      with:
       name: webapp

    - name: "Deploy to Azure Web App"
      uses: azure/webapps-deploy@v2
      with:
       app-name: ${{ env.APP_NAME }}
       package: "."
       publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Delete Artifact"
      uses: geekyeggo/delete-artifact@v2
      with:
       name: webapp